services:
  - type: web
    name: nocodepay
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: changeme12345
